spring:
  redis:
    host: 192.168.59.122
    port: 6379
    lettuce:
      pool:
        max-wait: 100000
        max-idle: 10
        max-active: 100
    timeout: 5000
  rabbitmq:
    host: 192.168.59.122
    port: 5672
    username: guest
    password: guest
    publisher-returns: true
    publisher-confirm-type: correlated
